const Map<String, dynamic> codes = {
    "AF": {"name": "Afghanistan", "alpha2Code": "AF", "alpha3Code": "AFG", "dial_code": "+93", "country_code": "fa_AF", "emoji": "🇦🇫"},
    "AL": {"name": "Albania", "alpha2Code": "AL", "dial_code": "+355", "country_code": "sq_AL", "alpha3Code": "ALB", "emoji": "🇦🇱"},
    "DZ": {"name": "Algeria", "alpha2Code": "DZ", "dial_code": "+213", "country_code": "ar_DZ", "alpha3Code": "DZA", "emoji": "🇩🇿"},
    "AS": {"name": "American Samoa", "alpha2Code": "AS", "alpha3Code": "ASM", "dial_code": "+1684", "country_code": "en_AS", "emoji": "🇦🇸"},
    "AD": {"name": "Andorra", "alpha2Code": "AD", "alpha3Code": "AND", "dial_code": "+376", "country_code": "ca_AD", "emoji": "🇦🇩"},
    "AO": {"name": "Angola", "alpha2Code": "AO", "alpha3Code": "AGO", "dial_code": "+244", "country_code": "pt_AO", "emoji": "🇦🇴"},
    "AI": {"name": "Anguilla", "alpha2Code": "AI", "alpha3Code": "AIA", "dial_code": "+1264", "country_code": "en_AI", "emoji": "🇦🇮"},
    "AQ": {"name": "Antarctica", "alpha2Code": "AQ", "alpha3Code": "ATA", "dial_code": "+672", "country_code": "en_AQ", "emoji": "🇦🇶"},
    "AG": {"name": "Antigua and Barbuda", "alpha2Code": "AG", "alpha3Code": "ATG", "dial_code": "+1268", "country_code": "en_AG", "emoji": "🇦🇬"},
    "AR": {"name": "Argentina", "alpha2Code": "AR", "dial_code": "+54", "country_code": "es_AR", "alpha3Code": "ARG", "emoji": "🇦🇷"},
    "AM": {"name": "Armenia", "alpha2Code": "AM", "dial_code": "+374", "country_code": "hy_AM", "alpha3Code": "ARM", "emoji": "🇦🇲"},
    "AW": {"name": "Aruba", "alpha2Code": "AW", "dial_code": "+297", "country_code": "nl_AW", "alpha3Code": "ABW", "emoji": "🇦🇼"},
    "AU": {"name": "Australia", "alpha2Code": "AU", "alpha3Code": "AUS", "dial_code": "+61", "country_code": "en_AU", "emoji": "🇦🇺"},
    "AT": {"name": "Austria", "alpha2Code": "AT", "alpha3Code": "AUT", "dial_code": "+43", "country_code": "de_AT", "emoji": "🇦🇹"},
    "AZ": {"name": "Azerbaijan", "alpha2Code": "AZ", "dial_code": "+994", "country_code": "az_AZ", "alpha3Code": "AZE", "emoji": "🇦🇿"},
    "BS": {"name": "Bahamas", "alpha2Code": "BS", "alpha3Code": "BHS", "dial_code": "+1242", "country_code": "en_BS", "emoji": "🇧🇸"},
    "BH": {"name": "Bahrain", "alpha2Code": "BH", "alpha3Code": "BHR", "dial_code": "+973", "country_code": "ar_BH", "emoji": "🇧🇭"},
    "BD": {"name": "Bangladesh", "alpha2Code": "BD", "alpha3Code": "BGD", "dial_code": "+880", "country_code": "bn_BD", "emoji": "🇧🇩"},
    "BB": {"name": "Barbados", "alpha2Code": "BB", "alpha3Code": "BRB", "dial_code": "+1246", "country_code": "en_BB", "emoji": "🇧🇧"},
    "BY": {"name": "Belarus", "alpha2Code": "BY", "alpha3Code": "BLR", "dial_code": "+375", "country_code": "be_BY", "emoji": "🇧🇾"},
    "BE": {"name": "Belgium", "alpha2Code": "BE", "dial_code": "+32", "country_code": "nl_BE", "alpha3Code": "BEL", "emoji": "🇧🇪"},
    "BZ": {"name": "Belize", "alpha2Code": "BZ", "alpha3Code": "BLZ", "dial_code": "+501", "country_code": "en_BZ", "emoji": "🇧🇿"},
    "BJ": {"name": "Benin", "alpha2Code": "BJ", "alpha3Code": "BEN", "dial_code": "+229", "country_code": "fr_BJ", "emoji": "🇧🇯"},
    "BM": {"name": "Bermuda", "alpha2Code": "BM", "alpha3Code": "BMU", "dial_code": "+1441", "country_code": "en_BM", "emoji": "🇧🇲"},
    "BT": {"name": "Bhutan", "alpha2Code": "BT", "alpha3Code": "BTN", "dial_code": "+975", "country_code": "dz_BT", "emoji": "🇧🇹"},
    "BO": {"name": "Bolivia", "alpha2Code": "BO", "alpha3Code": "BOL", "dial_code": "+591", "country_code": "es_BO", "emoji": "🇧🇴"},
    "BA": {"name": "Bosnia and Herzegovina", "alpha2Code": "BA", "alpha3Code": "BIH", "dial_code": "+387", "country_code": "bs_BA", "emoji": "🇧🇦"},
    "BW": {"name": "Botswana", "alpha2Code": "BW", "alpha3Code": "BWA", "dial_code": "+267", "country_code": "en_BW", "emoji": "🇧🇼"},
    "BR": {"name": "Brazil", "alpha2Code": "BR", "alpha3Code": "BRA", "dial_code": "+55", "country_code": "pt_BR", "emoji": "🇧🇷"},
    "IO": {"name": "British Indian Ocean Territory", "alpha2Code": "IO", "alpha3Code": "IOT", "dial_code": "+246", "country_code": "en_IO", "emoji": "🇮🇴"},
    "VG": {"name": "British Virgin Islands", "alpha2Code": "VG", "alpha3Code": "VGB", "dial_code": "+1284", "country_code": "en_VG", "emoji": "🇻🇬"},
    "BN": {"name": "Brunei", "alpha2Code": "BN", "alpha3Code": "BRN", "dial_code": "+673", "country_code": "ms_BN", "emoji": "🇧🇳"},
    "BG": {"name": "Bulgaria", "alpha2Code": "BG", "alpha3Code": "BGR", "dial_code": "+359", "country_code": "bg_BG", "emoji": "🇧🇬"},
    "BF": {"name": "Burkina Faso", "alpha2Code": "BF", "alpha3Code": "BFA", "dial_code": "+226", "country_code": "fr_BF", "emoji": "🇧🇫"},
    "BI": {"name": "Burundi", "alpha2Code": "BI", "alpha3Code": "BDI", "dial_code": "+257", "country_code": "fr_BI", "emoji": "🇧🇮"},
    "KH": {"name": "Cambodia", "alpha2Code": "KH", "alpha3Code": "KHM", "dial_code": "+855", "country_code": "km_KH", "emoji": "🇰🇭"},
    "CM": {"name": "Cameroon", "alpha2Code": "CM", "alpha3Code": "CMR", "dial_code": "+237", "country_code": "en_CM", "emoji": "🇨🇲"},
    "CA": {"name": "Canada", "alpha2Code": "CA", "alpha3Code": "CAN", "dial_code": "+1", "country_code": "en_CA", "emoji": "🇨🇦"},
    "CV": {"name": "Cape Verde", "alpha2Code": "CV", "alpha3Code": "CPV", "dial_code": "+238", "country_code": "pt_CV", "emoji": "🇨🇻"},
    "KY": {"name": "Cayman Islands", "alpha2Code": "KY", "alpha3Code": "CYM", "dial_code": "+1345", "country_code": "en_KY", "emoji": "🇰🇾"},
    "CF": {"name": "Central African Republic", "alpha2Code": "CF", "alpha3Code": "CAF", "dial_code": "+236", "country_code": "fr_CF", "emoji": "🇨🇫"},
    "TD": {"name": "Chad", "alpha2Code": "TD", "alpha3Code": "TCD", "dial_code": "+235", "country_code": "fr_TD", "emoji": "🇹🇩"},
    "CL": {"name": "Chile", "alpha2Code": "CL", "alpha3Code": "CHL", "dial_code": "+56", "country_code": "es_CL", "emoji": "🇨🇱"},
    "CN": {"name": "China", "alpha2Code": "CN", "alpha3Code": "CHN", "dial_code": "+86", "country_code": "zh_CN", "emoji": "🇨🇳"},
    "CX": {"name": "Christmas Island", "alpha2Code": "CX", "alpha3Code": "CXR", "dial_code": "+61", "country_code": "en_CX", "emoji": "🇨🇽"},
    "CC": {"name": "Cocos Islands", "alpha2Code": "CC", "alpha3Code": "CCK", "dial_code": "+61", "country_code": "en_CC", "emoji": "🇨🇨"},
    "CO": {"name": "Colombia", "alpha2Code": "CO", "alpha3Code": "COL", "dial_code": "+57", "country_code": "es_CO", "emoji": "🇨🇴"},
    "KM": {"name": "Comoros", "alpha2Code": "KM", "alpha3Code": "COM", "dial_code": "+269", "country_code": "ar_KM", "emoji": "🇰🇲"},
    "CK": {"name": "Cook Islands", "alpha2Code": "CK", "alpha3Code": "COK", "dial_code": "+682", "country_code": "en_CK", "emoji": "🇨🇰"},
    "CR": {"name": "Costa Rica", "alpha2Code": "CR", "alpha3Code": "CRI", "dial_code": "+506", "country_code": "es_CR", "emoji": "🇨🇷"},
    "HR": {"name": "Croatia", "alpha2Code": "HR", "alpha3Code": "HRV", "dial_code": "+385", "country_code": "hr_HR", "emoji": "🇭🇷"},
    "CU": {"name": "Cuba", "alpha2Code": "CU", "alpha3Code": "CUB", "dial_code": "+53", "country_code": "es_CU", "emoji": "🇨🇺"},
    "CW": {"name": "Curacao", "alpha2Code": "CW", "alpha3Code": "CUW", "dial_code": "+599", "country_code": "nl_CW", "emoji": "🇨🇼"},
    "CY": {"name": "Cyprus", "alpha2Code": "CY", "alpha3Code": "CYP", "dial_code": "+357", "country_code": "el_CY", "emoji": "🇨🇾"},
    "CZ": {"name": "Czech Republic", "alpha2Code": "CZ", "alpha3Code": "CZE", "dial_code": "+420", "country_code": "cs_CZ", "emoji": "🇨🇿"},
    "CD": {"name": "Democratic Republic of the Congo", "alpha2Code": "CD", "alpha3Code": "COD", "dial_code": "+243", "country_code": "fr_CD", "emoji": "🇨🇩"},
    "DK": {"name": "Denmark", "alpha2Code": "DK", "alpha3Code": "DNK", "dial_code": "+45", "country_code": "da_DK", "emoji": "🇩🇰"},
    "DJ": {"name": "Djibouti", "alpha2Code": "DJ", "alpha3Code": "DJI", "dial_code": "+253", "country_code": "fr_DJ", "emoji": "🇩🇯"},
    "DM": {"name": "Dominica", "alpha2Code": "DM", "alpha3Code": "DMA", "dial_code": "+1767", "country_code": "en_DM", "emoji": "🇩🇲"},
    "DO": {"name": "Dominican Republic", "alpha2Code": "DO", "alpha3Code": "DOM", "dial_code": "+1809", "country_code": "es_DO", "emoji": "🇩🇴"},
    "TL": {"name": "East Timor", "alpha2Code": "TL", "alpha3Code": "TLS", "dial_code": "+670", "country_code": "pt_TL", "emoji": "🇹🇱"},
    "EC": {"name": "Ecuador", "alpha2Code": "EC", "alpha3Code": "ECU", "dial_code": "+593", "country_code": "es_EC", "emoji": "🇪🇨"},
    "EG": {"name": "Egypt", "alpha2Code": "EG", "alpha3Code": "EGY", "dial_code": "+20", "country_code": "ar_EG", "emoji": "🇪🇬"},
    "SV": {"name": "El Salvador", "alpha2Code": "SV", "alpha3Code": "SLV", "dial_code": "+503", "country_code": "es_SV", "emoji": "🇸🇻"},
    "GQ": {"name": "Equatorial Guinea", "alpha2Code": "GQ", "alpha3Code": "GNQ", "dial_code": "+240", "country_code": "es_GQ", "emoji": "🇬🇶"},
    "ER": {"name": "Eritrea", "alpha2Code": "ER", "alpha3Code": "ERI", "dial_code": "+291", "country_code": "ti_ER", "emoji": "🇪🇷"},
    "EE": {"name": "Estonia", "alpha2Code": "EE", "alpha3Code": "EST", "dial_code": "+372", "country_code": "et_EE", "emoji": "🇪🇪"},
    "ET": {"name": "Ethiopia", "alpha2Code": "ET", "alpha3Code": "ETH", "dial_code": "+251", "country_code": "am_ET", "emoji": "🇪🇹"},
    "FK": {"name": "Falkland Islands", "alpha2Code": "FK", "alpha3Code": "FLK", "dial_code": "+500", "country_code": "en_FK", "emoji": "🇫🇰"},
    "FO": {"name": "Faroe Islands", "alpha2Code": "FO", "alpha3Code": "FRO", "dial_code": "+298", "country_code": "fo_FO", "emoji": "🇫🇴"},
    "FJ": {"name": "Fiji", "alpha2Code": "FJ", "alpha3Code": "FJI", "dial_code": "+679", "country_code": "en_FJ", "emoji": "🇫🇯"},
    "FI": {"name": "Finland", "alpha2Code": "FI", "alpha3Code": "FIN", "dial_code": "+358", "country_code": "fi_FI", "emoji": "🇫🇮"},
    "FR": {"name": "France", "alpha2Code": "FR", "alpha3Code": "FRA", "dial_code": "+33", "country_code": "fr_FR", "emoji": "🇫🇷"},
    "PF": {"name": "French Polynesia", "alpha2Code": "PF", "alpha3Code": "PYF", "dial_code": "+689", "country_code": "fr_PF", "emoji": "🇵🇫"},
    "TF": {"name": "French Southern Territories", "alpha2Code": "TF", "alpha3Code": "ATF", "dial_code": "+262", "country_code": "fr_TF", "emoji": "🇹🇫"},
    "GA": {"name": "Gabon", "alpha2Code": "GA", "alpha3Code": "GAB", "dial_code": "+241", "country_code": "fr_GA", "emoji": "🇬🇦"},
    "GM": {"name": "Gambia", "alpha2Code": "GM", "alpha3Code": "GMB", "dial_code": "+220", "country_code": "en_GM", "emoji": "🇬🇲"},
    "GE": {"name": "Georgia", "alpha2Code": "GE", "alpha3Code": "GEO", "dial_code": "+995", "country_code": "ka_GE", "emoji": "🇬🇪"},
    "DE": {"name": "Germany", "alpha2Code": "DE", "alpha3Code": "DEU", "dial_code": "+49", "country_code": "de_DE", "emoji": "🇩🇪"},
    "GH": {"name": "Ghana", "alpha2Code": "GH", "alpha3Code": "GHA", "dial_code": "+233", "country_code": "en_GH", "emoji": "🇬🇭"},
    "GI": {"name": "Gibraltar", "alpha2Code": "GI", "alpha3Code": "GIB", "dial_code": "+350", "country_code": "en_GI", "emoji": "🇬🇮"},
    "GR": {"name": "Greece", "alpha2Code": "GR", "alpha3Code": "GRC", "dial_code": "+30", "country_code": "el_GR", "emoji": "🇬🇷"},
    "GL": {"name": "Greenland", "alpha2Code": "GL", "alpha3Code": "GRL", "dial_code": "+299", "country_code": "kl_GL", "emoji": "🇬🇱"},
    "GD": {"name": "Grenada", "alpha2Code": "GD", "alpha3Code": "GRD", "dial_code": "+1473", "country_code": "en_GD", "emoji": "🇬🇩"},
    "GP": {"name": "Guadeloupe", "alpha2Code": "GP", "alpha3Code": "GLP", "dial_code": "+590", "country_code": "fr_GP", "emoji": "🇬🇵"},
    "GU": {"name": "Guam", "alpha2Code": "GU", "alpha3Code": "GUM", "dial_code": "+1671", "country_code": "en_GU", "emoji": "🇬🇺"},
    "GT": {"name": "Guatemala", "alpha2Code": "GT", "alpha3Code": "GTM", "dial_code": "+502", "country_code": "es_GT", "emoji": "🇬🇹"},
    "GG": {"name": "Guernsey", "alpha2Code": "GG", "alpha3Code": "GGY", "dial_code": "+44", "country_code": "en_GG", "emoji": "🇬🇬"},
    "GN": {"name": "Guinea", "alpha2Code": "GN", "alpha3Code": "GIN", "dial_code": "+224", "country_code": "fr_GN", "emoji": "🇬🇳"},
    "GW": {"name": "Guinea-Bissau", "alpha2Code": "GW", "alpha3Code": "GNB", "dial_code": "+245", "country_code": "pt_GW", "emoji": "🇬🇼"},
    "GY": {"name": "Guyana", "alpha2Code": "GY", "alpha3Code": "GUY", "dial_code": "+592", "country_code": "en_GY", "emoji": "🇬🇾"},
    "HT": {"name": "Haiti", "alpha2Code": "HT", "alpha3Code": "HTI", "dial_code": "+509", "country_code": "fr_HT", "emoji": "🇭🇹"},
    "HN": {"name": "Honduras", "alpha2Code": "HN", "alpha3Code": "HND", "dial_code": "+504", "country_code": "es_HN", "emoji": "🇭🇳"},
    "HK": {"name": "Hong Kong", "alpha2Code": "HK", "alpha3Code": "HKG", "dial_code": "+852", "country_code": "zh_HK", "emoji": "🇭🇰"},
    "HU": {"name": "Hungary", "alpha2Code": "HU", "alpha3Code": "HUN", "dial_code": "+36", "country_code": "hu_HU", "emoji": "🇭🇺"},
    "IS": {"name": "Iceland", "alpha2Code": "IS", "alpha3Code": "ISL", "dial_code": "+354", "country_code": "is_IS", "emoji": "🇮🇸"},
    "IN": {"name": "India", "alpha2Code": "IN", "alpha3Code": "IND", "dial_code": "+91", "country_code": "hi_IN", "emoji": "🇮🇳"},
    "ID": {"name": "Indonesia", "alpha2Code": "ID", "alpha3Code": "IDN", "dial_code": "+62", "country_code": "id_ID", "emoji": "🇮🇩"},
    "IR": {"name": "Iran", "alpha2Code": "IR", "alpha3Code": "IRN", "dial_code": "+98", "country_code": "fa_IR", "emoji": "🇮🇷"},
    "IQ": {"name": "Iraq", "alpha2Code": "IQ", "alpha3Code": "IRQ", "dial_code": "+964", "country_code": "ar_IQ", "emoji": "🇮🇶"},
    "IE": {"name": "Ireland", "alpha2Code": "IE", "alpha3Code": "IRL", "dial_code": "+353", "country_code": "en_IE", "emoji": "🇮🇪"},
    "IM": {"name": "Isle of Man", "alpha2Code": "IM", "alpha3Code": "IMN", "dial_code": "+44", "country_code": "en_IM", "emoji": "🇮🇲"},
    "IL": {"name": "Israel", "alpha2Code": "IL", "alpha3Code": "ISR", "dial_code": "+972", "country_code": "he_IL", "emoji": "🇮🇱"},
    "IT": {"name": "Italy", "alpha2Code": "IT", "alpha3Code": "ITA", "dial_code": "+39", "country_code": "it_IT", "emoji": "🇮🇹"},
    "CI": {"name": "Ivory Coast", "alpha2Code": "CI", "alpha3Code": "CIV", "dial_code": "+225", "country_code": "fr_CI", "emoji": "🇨🇮"},
    "JM": {"name": "Jamaica", "alpha2Code": "JM", "alpha3Code": "JAM", "dial_code": "+1876", "country_code": "en_JM", "emoji": "🇯🇲"},
    "JP": {"name": "Japan", "alpha2Code": "JP", "alpha3Code": "JPN", "dial_code": "+81", "country_code": "ja_JP", "emoji": "🇯🇵"},
    "JE": {"name": "Jersey", "alpha2Code": "JE", "alpha3Code": "JEY", "dial_code": "+44", "country_code": "en_JE", "emoji": "🇯🇪"},
    "JO": {"name": "Jordan", "alpha2Code": "JO", "alpha3Code": "JOR", "dial_code": "+962", "country_code": "ar_JO", "emoji": "🇯🇴"},
    "KZ": {"name": "Kazakhstan", "alpha2Code": "KZ", "alpha3Code": "KAZ", "dial_code": "+7", "country_code": "ru_KZ", "emoji": "🇰🇿"},
    "KE": {"name": "Kenya", "alpha2Code": "KE", "alpha3Code": "KEN", "dial_code": "+254", "country_code": "sw_KE", "emoji": "🇰🇪"},
    "KI": {"name": "Kiribati", "alpha2Code": "KI", "alpha3Code": "KIR", "dial_code": "+686", "country_code": "en_KI", "emoji": "🇰🇮"},
    "XK": {"name": "Kosovo", "alpha2Code": "XK", "alpha3Code": "XKX", "dial_code": "+383", "country_code": "sq_XK", "emoji": "🇽🇰"},
    "KW": {"name": "Kuwait", "alpha2Code": "KW", "alpha3Code": "KWT", "dial_code": "+965", "country_code": "ar_KW", "emoji": "🇰🇼"},
    "KG": {"name": "Kyrgyzstan", "alpha2Code": "KG", "alpha3Code": "KGZ", "dial_code": "+996", "country_code": "ky_KG", "emoji": "🇰🇬"},
    "LA": {"name": "Laos", "alpha2Code": "LA", "alpha3Code": "LAO", "dial_code": "+856", "country_code": "lo_LA", "emoji": "🇱🇦"},
    "LV": {"name": "Latvia", "alpha2Code": "LV", "alpha3Code": "LVA", "dial_code": "+371", "country_code": "lv_LV", "emoji": "🇱🇻"},
    "LB": {"name": "Lebanon", "alpha2Code": "LB", "alpha3Code": "LBN", "dial_code": "+961", "country_code": "ar_LB", "emoji": "🇱🇧"},
    "LS": {"name": "Lesotho", "alpha2Code": "LS", "alpha3Code": "LSO", "dial_code": "+266", "country_code": "en_LS", "emoji": "🇱🇸"},
    "LR": {"name": "Liberia", "alpha2Code": "LR", "alpha3Code": "LBR", "dial_code": "+231", "country_code": "en_LR", "emoji": "🇱🇷"},
    "LY": {"name": "Libya", "alpha2Code": "LY", "alpha3Code": "LBY", "dial_code": "+218", "country_code": "ar_LY", "emoji": "🇱🇾"},
    "LI": {"name": "Liechtenstein", "alpha2Code": "LI", "alpha3Code": "LIE", "dial_code": "+423", "country_code": "de_LI", "emoji": "🇱🇮"},
    "LT": {"name": "Lithuania", "alpha2Code": "LT", "alpha3Code": "LTU", "dial_code": "+370", "country_code": "lt_LT", "emoji": "🇱🇹"},
    "LU": {"name": "Luxembourg", "alpha2Code": "LU", "alpha3Code": "LUX", "dial_code": "+352", "country_code": "fr_LU", "emoji": "🇱🇺"},
    "MO": {"name": "Macau", "alpha2Code": "MO", "alpha3Code": "MAC", "dial_code": "+853", "country_code": "zh_MO", "emoji": "🇲🇴"},
    "MK": {"name": "Macedonia", "alpha2Code": "MK", "alpha3Code": "MKD", "dial_code": "+389", "country_code": "mk_MK", "emoji": "🇲🇰"},
    "MG": {"name": "Madagascar", "alpha2Code": "MG", "alpha3Code": "MDG", "dial_code": "+261", "country_code": "fr_MG", "emoji": "🇲🇬"},
    "MW": {"name": "Malawi", "alpha2Code": "MW", "alpha3Code": "MWI", "dial_code": "+265", "country_code": "en_MW", "emoji": "🇲🇼"},
    "MY": {"name": "Malaysia", "alpha2Code": "MY", "alpha3Code": "MYS", "dial_code": "+60", "country_code": "ms_MY", "emoji": "🇲🇾"},
    "MV": {"name": "Maldives", "alpha2Code": "MV", "alpha3Code": "MDV", "dial_code": "+960", "country_code": "dv_MV", "emoji": "🇲🇻"},
    "ML": {"name": "Mali", "alpha2Code": "ML", "alpha3Code": "MLI", "dial_code": "+223", "country_code": "fr_ML", "emoji": "🇲🇱"},
    "MT": {"name": "Malta", "alpha2Code": "MT", "alpha3Code": "MLT", "dial_code": "+356", "country_code": "mt_MT", "emoji": "🇲🇹"},
    "MH": {"name": "Marshall Islands", "alpha2Code": "MH", "alpha3Code": "MHL", "dial_code": "+692", "country_code": "en_MH", "emoji": "🇲🇭"},
    "MQ": {"name": "Martinique", "alpha2Code": "MQ", "alpha3Code": "MTQ", "dial_code": "+596", "country_code": "fr_MQ", "emoji": "🇲🇶"},
    "MR": {"name": "Mauritania", "alpha2Code": "MR", "alpha3Code": "MRT", "dial_code": "+222", "country_code": "ar_MR", "emoji": "🇲🇷"},
    "MU": {"name": "Mauritius", "alpha2Code": "MU", "alpha3Code": "MUS", "dial_code": "+230", "country_code": "en_MU", "emoji": "🇲🇺"},
    "YT": {"name": "Mayotte", "alpha2Code": "YT", "alpha3Code": "MYT", "dial_code": "+262", "country_code": "fr_YT", "emoji": "🇾🇹"},
    "MX": {"name": "Mexico", "alpha2Code": "MX", "alpha3Code": "MEX", "dial_code": "+52", "country_code": "es_MX", "emoji": "🇲🇽"},
    "FM": {"name": "Micronesia", "alpha2Code": "FM", "alpha3Code": "FSM", "dial_code": "+691", "country_code": "en_FM", "emoji": "🇫🇲"},
    "MD": {"name": "Moldova", "alpha2Code": "MD", "alpha3Code": "MDA", "dial_code": "+373", "country_code": "ro_MD", "emoji": "🇲🇩"},
    "MC": {"name": "Monaco", "alpha2Code": "MC", "alpha3Code": "MCO", "dial_code": "+377", "country_code": "fr_MC", "emoji": "🇲🇨"},
    "MN": {"name": "Mongolia", "alpha2Code": "MN", "alpha3Code": "MNG", "dial_code": "+976", "country_code": "mn_MN", "emoji": "🇲🇳"},
    "ME": {"name": "Montenegro", "alpha2Code": "ME", "alpha3Code": "MNE", "dial_code": "+382", "country_code": "sr_ME", "emoji": "🇲🇪"},
    "MS": {"name": "Montserrat", "alpha2Code": "MS", "alpha3Code": "MSR", "dial_code": "+1664", "country_code": "en_MS", "emoji": "🇲🇸"},
    "MA": {"name": "Morocco", "alpha2Code": "MA", "alpha3Code": "MAR", "dial_code": "+212", "country_code": "ar_MA", "emoji": "🇲🇦"},
    "MZ": {"name": "Mozambique", "alpha2Code": "MZ", "alpha3Code": "MOZ", "dial_code": "+258", "country_code": "pt_MZ", "emoji": "🇲🇿"},
    "MM": {"name": "Myanmar", "alpha2Code": "MM", "alpha3Code": "MMR", "dial_code": "+95", "country_code": "my_MM", "emoji": "🇲🇲"},
    "NA": {"name": "Namibia", "alpha2Code": "NA", "alpha3Code": "NAM", "dial_code": "+264", "country_code": "en_NA", "emoji": "🇳🇦"},
    "NR": {"name": "Nauru", "alpha2Code": "NR", "alpha3Code": "NRU", "dial_code": "+674", "country_code": "en_NR", "emoji": "🇳🇷"},
    "NP": {"name": "Nepal", "alpha2Code": "NP", "alpha3Code": "NPL", "dial_code": "+977", "country_code": "ne_NP", "emoji": "🇳🇵"},
    "NL": {"name": "Netherlands", "alpha2Code": "NL", "alpha3Code": "NLD", "dial_code": "+31", "country_code": "nl_NL", "emoji": "🇳🇱"},
    "NC": {"name": "New Caledonia", "alpha2Code": "NC", "alpha3Code": "NCL", "dial_code": "+687", "country_code": "fr_NC", "emoji": "🇳🇨"},
    "NZ": {"name": "New Zealand", "alpha2Code": "NZ", "alpha3Code": "NZL", "dial_code": "+64", "country_code": "en_NZ", "emoji": "🇳🇿"},
    "NI": {"name": "Nicaragua", "alpha2Code": "NI", "alpha3Code": "NIC", "dial_code": "+505", "country_code": "es_NI", "emoji": "🇳🇮"},
    "NE": {"name": "Niger", "alpha2Code": "NE", "alpha3Code": "NER", "dial_code": "+227", "country_code": "fr_NE", "emoji": "🇳🇪"},
    "NG": {"name": "Nigeria", "alpha2Code": "NG", "alpha3Code": "NGA", "dial_code": "+234", "country_code": "en_NG", "emoji": "🇳🇬"},
    "NU": {"name": "Niue", "alpha2Code": "NU", "alpha3Code": "NIU", "dial_code": "+683", "country_code": "en_NU", "emoji": "🇳🇺"},
    "NF": {"name": "Norfolk Island", "alpha2Code": "NF", "alpha3Code": "NFK", "dial_code": "+672", "country_code": "en_NF", "emoji": "🇳🇫"},
    "KP": {"name": "North Korea", "alpha2Code": "KP", "alpha3Code": "PRK", "dial_code": "+850", "country_code": "ko_KP", "emoji": "🇰🇵"},
    "MP": {"name": "Northern Mariana Islands", "alpha2Code": "MP", "alpha3Code": "MNP", "dial_code": "+1670", "country_code": "en_MP", "emoji": "🇲🇵"},
    "NO": {"name": "Norway", "alpha2Code": "NO", "alpha3Code": "NOR", "dial_code": "+47", "country_code": "no_NO", "emoji": "🇳🇴"},
    "OM": {"name": "Oman", "alpha2Code": "OM", "alpha3Code": "OMN", "dial_code": "+968", "country_code": "ar_OM", "emoji": "🇴🇲"},
    "PK": {"name": "Pakistan", "alpha2Code": "PK", "alpha3Code": "PAK", "dial_code": "+92", "country_code": "ur_PK", "emoji": "🇵🇰"},
    "PW": {"name": "Palau", "alpha2Code": "PW", "alpha3Code": "PLW", "dial_code": "+680", "country_code": "en_PW", "emoji": "🇵🇼"},
    "PS": {"name": "Palestine", "alpha2Code": "PS", "alpha3Code": "PSE", "dial_code": "+970", "country_code": "ar_PS", "emoji": "🇵🇸"},
    "PA": {"name": "Panama", "alpha2Code": "PA", "alpha3Code": "PAN", "dial_code": "+507", "country_code": "es_PA", "emoji": "🇵🇦"},
    "PG": {"name": "Papua New Guinea", "alpha2Code": "PG", "alpha3Code": "PNG", "dial_code": "+675", "country_code": "en_PG", "emoji": "🇵🇬"},
    "PY": {"name": "Paraguay", "alpha2Code": "PY", "alpha3Code": "PRY", "dial_code": "+595", "country_code": "es_PY", "emoji": "🇵🇾"},
    "PE": {"name": "Peru", "alpha2Code": "PE", "alpha3Code": "PER", "dial_code": "+51", "country_code": "es_PE", "emoji": "🇵🇪"},
    "PH": {"name": "Philippines", "alpha2Code": "PH", "alpha3Code": "PHL", "dial_code": "+63", "country_code": "en_PH", "emoji": "🇵🇭"},
    "PN": {"name": "Pitcairn", "alpha2Code": "PN", "alpha3Code": "PCN", "dial_code": "+64", "country_code": "en_PN", "emoji": "🇵🇳"},
    "PL": {"name": "Poland", "alpha2Code": "PL", "alpha3Code": "POL", "dial_code": "+48", "country_code": "pl_PL", "emoji": "🇵🇱"},
    "PT": {"name": "Portugal", "alpha2Code": "PT", "alpha3Code": "PRT", "dial_code": "+351", "country_code": "pt_PT", "emoji": "🇵🇹"},
    "PR": {"name": "Puerto Rico", "alpha2Code": "PR", "alpha3Code": "PRI", "dial_code": "+1939", "country_code": "es_PR", "emoji": "🇵🇷"},
    "QA": {"name": "Qatar", "alpha2Code": "QA", "alpha3Code": "QAT", "dial_code": "+974", "country_code": "ar_QA", "emoji": "🇶🇦"},
    "CG": {"name": "Republic of the Congo", "alpha2Code": "CG", "alpha3Code": "COG", "dial_code": "+242", "country_code": "fr_CG", "emoji": "🇨🇬"},
    "RE": {"name": "Reunion", "alpha2Code": "RE", "alpha3Code": "REU", "dial_code": "+262", "country_code": "fr_RE", "emoji": "🇷🇪"},
    "RO": {"name": "Romania", "alpha2Code": "RO", "alpha3Code": "ROU", "dial_code": "+40", "country_code": "ro_RO", "emoji": "🇷🇴"},
    "RU": {"name": "Russia", "alpha2Code": "RU", "alpha3Code": "RUS", "dial_code": "+7", "country_code": "ru_RU", "emoji": "🇷🇺"},
    "RW": {"name": "Rwanda", "alpha2Code": "RW", "alpha3Code": "RWA", "dial_code": "+250", "country_code": "rw_RW", "emoji": "🇷🇼"},
    "BL": {"name": "Saint Barthelemy", "alpha2Code": "BL", "alpha3Code": "BLM", "dial_code": "+590", "country_code": "fr_BL", "emoji": "🇧🇱"},
    "SH": {"name": "Saint Helena", "alpha2Code": "SH", "alpha3Code": "SHN", "dial_code": "+290", "country_code": "en_SH", "emoji": "🇸🇭"},
    "KN": {"name": "Saint Kitts and Nevis", "alpha2Code": "KN", "alpha3Code": "KNA", "dial_code": "+1869", "country_code": "en_KN", "emoji": "🇰🇳"},
    "LC": {"name": "Saint Lucia", "alpha2Code": "LC", "alpha3Code": "LCA", "dial_code": "+1758", "country_code": "en_LC", "emoji": "🇱🇨"},
    "MF": {"name": "Saint Martin", "alpha2Code": "MF", "alpha3Code": "MAF", "dial_code": "+590", "country_code": "fr_MF", "emoji": "🇲🇫"},
    "PM": {"name": "Saint Pierre and Miquelon", "alpha2Code": "PM", "alpha3Code": "SPM", "dial_code": "+508", "country_code": "fr_PM", "emoji": "🇵🇲"},
    "VC": {"name": "Saint Vincent and the Grenadines", "alpha2Code": "VC", "alpha3Code": "VCT", "dial_code": "+1784", "country_code": "en_VC", "emoji": "🇻🇨"},
    "WS": {"name": "Samoa", "alpha2Code": "WS", "alpha3Code": "WSM", "dial_code": "+685", "country_code": "sm_WS", "emoji": "🇼🇸"},
    "SM": {"name": "San Marino", "alpha2Code": "SM", "alpha3Code": "SMR", "dial_code": "+378", "country_code": "it_SM", "emoji": "🇸🇲"},
    "ST": {"name": "Sao Tome and Principe", "alpha2Code": "ST", "alpha3Code": "STP", "dial_code": "+239", "country_code": "pt_ST", "emoji": "🇸🇹"},
    "SA": {"name": "Saudi Arabia", "alpha2Code": "SA", "alpha3Code": "SAU", "dial_code": "+966", "country_code": "ar_SA", "emoji": "🇸🇦"},
    "SN": {"name": "Senegal", "alpha2Code": "SN", "alpha3Code": "SEN", "dial_code": "+221", "country_code": "fr_SN", "emoji": "🇸🇳"},
    "RS": {"name": "Serbia", "alpha2Code": "RS", "alpha3Code": "SRB", "dial_code": "+381", "country_code": "sr_RS", "emoji": "🇷🇸"},
    "SC": {"name": "Seychelles", "alpha2Code": "SC", "alpha3Code": "SYC", "dial_code": "+248", "country_code": "en_SC", "emoji": "🇸🇨"},
    "SL": {"name": "Sierra Leone", "alpha2Code": "SL", "alpha3Code": "SLE", "dial_code": "+232", "country_code": "en_SL", "emoji": "🇸🇱"},
    "SG": {"name": "Singapore", "alpha2Code": "SG", "alpha3Code": "SGP", "dial_code": "+65", "country_code": "zh_SG", "emoji": "🇸🇬"},
    "SX": {"name": "Sint Maarten", "alpha2Code": "SX", "alpha3Code": "SXM", "dial_code": "+1721", "country_code": "nl_SX", "emoji": "🇸🇽"},
    "SK": {"name": "Slovakia", "alpha2Code": "SK", "alpha3Code": "SVK", "dial_code": "+421", "country_code": "sk_SK", "emoji": "🇸🇰"},
    "SI": {"name": "Slovenia", "alpha2Code": "SI", "alpha3Code": "SVN", "dial_code": "+386", "country_code": "sl_SI", "emoji": "🇸🇮"},
    "SB": {"name": "Solomon Islands", "alpha2Code": "SB", "alpha3Code": "SLB", "dial_code": "+677", "country_code": "en_SB", "emoji": "🇸🇧"},
    "SO": {"name": "Somalia", "alpha2Code": "SO", "alpha3Code": "SOM", "dial_code": "+252", "country_code": "so_SO", "emoji": "🇸🇴"},
    "ZA": {"name": "South Africa", "alpha2Code": "ZA", "alpha3Code": "ZAF", "dial_code": "+27", "country_code": "en_ZA", "emoji": "🇿🇦"},
    "GS": {"name": "South Georgia and the South Sandwich Islands", "alpha2Code": "GS", "alpha3Code": "SGS", "dial_code": "+500", "country_code": "en_GS", "emoji": "🇬🇸"},
    "KR": {"name": "South Korea", "alpha2Code": "KR", "alpha3Code": "KOR", "dial_code": "+82", "country_code": "ko_KR", "emoji": "🇰🇷"},
    "SS": {"name": "South Sudan", "alpha2Code": "SS", "alpha3Code": "SSD", "dial_code": "+211", "country_code": "en_SS", "emoji": "🇸🇸"},
    "ES": {"name": "Spain", "alpha2Code": "ES", "alpha3Code": "ESP", "dial_code": "+34", "country_code": "es_ES", "emoji": "🇪🇸"},
    "LK": {"name": "Sri Lanka", "alpha2Code": "LK", "alpha3Code": "LKA", "dial_code": "+94", "country_code": "si_LK", "emoji": "🇱🇰"},
    "SD": {"name": "Sudan", "alpha2Code": "SD", "alpha3Code": "SDN", "dial_code": "+249", "country_code": "ar_SD", "emoji": "🇸🇩"},
    "SR": {"name": "Suriname", "alpha2Code": "SR", "alpha3Code": "SUR", "dial_code": "+597", "country_code": "nl_SR", "emoji": "🇸🇷"},
    "SJ": {"name": "Svalbard and Jan Mayen", "alpha2Code": "SJ", "alpha3Code": "SJM", "dial_code": "+47", "country_code": "no_SJ", "emoji": "🇸🇯"},
    "SZ": {"name": "Swaziland", "alpha2Code": "SZ", "alpha3Code": "SWZ", "dial_code": "+268", "country_code": "en_SZ", "emoji": "🇸🇿"},
    "SE": {"name": "Sweden", "alpha2Code": "SE", "alpha3Code": "SWE", "dial_code": "+46", "country_code": "sv_SE", "emoji": "🇸🇪"},
    "CH": {"name": "Switzerland", "alpha2Code": "CH", "alpha3Code": "CHE", "dial_code": "+41", "country_code": "de_CH", "emoji": "🇨🇭"},
    "SY": {"name": "Syria", "alpha2Code": "SY", "alpha3Code": "SYR", "dial_code": "+963", "country_code": "ar_SY", "emoji": "🇸🇾"},
    "TW": {"name": "Taiwan", "alpha2Code": "TW", "alpha3Code": "TWN", "dial_code": "+886", "country_code": "zh_TW", "emoji": "🇹🇼"},
    "TJ": {"name": "Tajikistan", "alpha2Code": "TJ", "alpha3Code": "TJK", "dial_code": "+992", "country_code": "tg_TJ", "emoji": "🇹🇯"},
    "TZ": {"name": "Tanzania", "alpha2Code": "TZ", "alpha3Code": "TZA", "dial_code": "+255", "country_code": "sw_TZ", "emoji": "🇹🇿"},
    "TH": {"name": "Thailand", "alpha2Code": "TH", "alpha3Code": "THA", "dial_code": "+66", "country_code": "th_TH", "emoji": "🇹🇭"},
    "TG": {"name": "Togo", "alpha2Code": "TG", "alpha3Code": "TGO", "dial_code": "+228", "country_code": "fr_TG", "emoji": "🇹🇬"},
    "TK": {"name": "Tokelau", "alpha2Code": "TK", "alpha3Code": "TKL", "dial_code": "+690", "country_code": "en_TK", "emoji": "🇹🇰"},
    "TO": {"name": "Tonga", "alpha2Code": "TO", "alpha3Code": "TON", "dial_code": "+676", "country_code": "en_TO", "emoji": "🇹🇴"},
    "TT": {"name": "Trinidad and Tobago", "alpha2Code": "TT", "alpha3Code": "TTO", "dial_code": "+1868", "country_code": "en_TT", "emoji": "🇹🇹"},
    "TN": {"name": "Tunisia", "alpha2Code": "TN", "alpha3Code": "TUN", "dial_code": "+216", "country_code": "ar_TN", "emoji": "🇹🇳"},
    "TR": {"name": "Turkey", "alpha2Code": "TR", "alpha3Code": "TUR", "dial_code": "+90", "country_code": "tr_TR", "emoji": "🇹🇷"},
    "TM": {"name": "Turkmenistan", "alpha2Code": "TM", "alpha3Code": "TKM", "dial_code": "+993", "country_code": "tk_TM", "emoji": "🇹🇲"},
    "TC": {"name": "Turks and Caicos Islands", "alpha2Code": "TC", "alpha3Code": "TCA", "dial_code": "+1649", "country_code": "en_TC", "emoji": "🇹🇨"},
    "TV": {"name": "Tuvalu", "alpha2Code": "TV", "alpha3Code": "TUV", "dial_code": "+688", "country_code": "en_TV", "emoji": "🇹🇻"},
    "VI": {"name": "U.S. Virgin Islands", "alpha2Code": "VI", "alpha3Code": "VIR", "dial_code": "+1340", "country_code": "en_VI", "emoji": "🇻🇮"},
    "UG": {"name": "Uganda", "alpha2Code": "UG", "alpha3Code": "UGA", "dial_code": "+256", "country_code": "sw_UG", "emoji": "🇺🇬"},
    "UA": {"name": "Ukraine", "alpha2Code": "UA", "alpha3Code": "UKR", "dial_code": "+380", "country_code": "uk_UA", "emoji": "🇺🇦"},
    "AE": {"name": "United Arab Emirates", "alpha2Code": "AE", "alpha3Code": "ARE", "dial_code": "+971", "country_code": "ar_AE", "emoji": "🇦🇪"},
    "GB": {"name": "United Kingdom", "alpha2Code": "GB", "alpha3Code": "GBR", "dial_code": "+44", "country_code": "en_GB", "emoji": "🇬🇧"},
    "US": {"name": "United States", "alpha2Code": "US", "alpha3Code": "USA", "dial_code": "+1", "country_code": "en_US", "emoji": "🇺🇸"},
    "UY": {"name": "Uruguay", "alpha2Code": "UY", "alpha3Code": "URY", "dial_code": "+598", "country_code": "es_UY", "emoji": "🇺🇾"},
    "UZ": {"name": "Uzbekistan", "alpha2Code": "UZ", "alpha3Code": "UZB", "dial_code": "+998", "country_code": "uz_UZ", "emoji": "🇺🇿"},
    "VU": {"name": "Vanuatu", "alpha2Code": "VU", "alpha3Code": "VUT", "dial_code": "+678", "country_code": "bi_VU", "emoji": "🇻🇺"},
    "VA": {"name": "Vatican", "alpha2Code": "VA", "alpha3Code": "VAT", "dial_code": "+379", "country_code": "la_VA", "emoji": "🇻🇦"},
    "VE": {"name": "Venezuela", "alpha2Code": "VE", "alpha3Code": "VEN", "dial_code": "+58", "country_code": "es_VE", "emoji": "🇻🇪"},
    "VN": {"name": "Vietnam", "alpha2Code": "VN", "alpha3Code": "VNM", "dial_code": "+84", "country_code": "vi_VN", "emoji": "🇻🇳"},
    "WF": {"name": "Wallis and Futuna", "alpha2Code": "WF", "alpha3Code": "WLF", "dial_code": "+681", "country_code": "fr_WF", "emoji": "🇼🇫"},
    "EH": {"name": "Western Sahara", "alpha2Code": "EH", "alpha3Code": "ESH", "dial_code": "+212", "country_code": "es_EH", "emoji": "🇪🇭"},
    "YE": {"name": "Yemen", "alpha2Code": "YE", "alpha3Code": "YEM", "dial_code": "+967", "country_code": "ar_YE", "emoji": "🇾🇪"},
    "ZM": {"name": "Zambia", "alpha2Code": "ZM", "alpha3Code": "ZMB", "dial_code": "+260", "country_code": "en_ZM", "emoji": "🇿🇲"},
    "ZW": {"name": "Zimbabwe", "alpha2Code": "ZW", "alpha3Code": "ZWE", "dial_code": "+263", "country_code": "en_ZW", "emoji": "🇿🇼"}
};
